spring:
  h2:
    console.enabled: true
  # sql:
  #   init.mode: always
  datasource:
    # url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:./data
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true